# Generated by Django 5.2.5 on 2026-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='rated_at',
            field=models.DateTimeField(blank=True, help_text='When review was submitted', null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='review_text',
            field=models.TextField(blank=True, default='', help_text='Customer review text'),
        ),
    ]
