# Generated by Django 5.2.5 on 2026-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_orderedproduct_rated_at_orderedproduct_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='rated_at',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='review_text',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='auto_calculate_rental_prices',
            field=models.BooleanField(default=True, help_text='Ã¢Å“Â¨ Automatically calculate all rental prices (base Ãƒâ€” days)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_buy_offer_price',
            field=models.IntegerField(default=0, help_text='Option-specific buy offer (0 = use product buy_offer_price) - Auto: base Ãƒâ€” 40'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_buy_price',
            field=models.IntegerField(default=0, help_text='Option-specific buy price (0 = use product buy_price) - Auto: base Ãƒâ€” 50'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_14_days',
            field=models.IntegerField(default=0, help_text='Rental price for 14 days (auto: base Ãƒâ€” 14)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_1_day',
            field=models.IntegerField(default=0, help_text='Rental price for 1 day (auto: base Ãƒâ€” 1)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_2_days',
            field=models.IntegerField(default=0, help_text='Rental price for 2 days (auto: base Ãƒâ€” 2)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_30_days',
            field=models.IntegerField(default=0, help_text='Rental price for 30 days (auto: base Ãƒâ€” 30)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_3_days',
            field=models.IntegerField(default=0, help_text='Rental price for 3 days (auto: base Ãƒâ€” 3)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_rent_7_days',
            field=models.IntegerField(default=0, help_text='Rental price for 7 days (auto: base Ãƒâ€” 7)'),
        ),
    ]
