# Generated by Django 5.2.5 on 2026-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_orderedproduct_rated_at_orderedproduct_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='rental_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='rental_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='buy', max_length=10),
        ),
    ]
