# Generated by Django 5.2.5 on 2026-03-09 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_add_product_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum cart total (in rupees) to use this coupon",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap on discount (for percentage coupons); leave blank for no cap",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(help_text="Coupon valid from")),
                ("valid_until", models.DateTimeField(help_text="Coupon valid until")),
                (
                    "usage_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of times this coupon can be used (0 = unlimited)",
                    ),
                ),
                ("used_count", models.IntegerField(default=0)),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only users with no previous orders can use this coupon",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Coupon Usage",
                "verbose_name_plural": "Coupon Usages",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="adminnotificationlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Send push notification",
                "verbose_name_plural": "Send push notifications",
            },
        ),
        migrations.RemoveConstraint(
            model_name="servicesubcategory",
            name="backend_servicesubcategory_category_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="userdevice",
            name="backend_userdevice_user_fcm_token_unique",
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.IntegerField(
                default=0, help_text="Discount applied from coupon (in rupees)"
            ),
        ),
        migrations.AlterField(
            model_name="homebanner",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="Soft delete", null=True),
        ),
        migrations.AlterUniqueTogether(
            name="servicesubcategory",
            unique_together={("category", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="userdevice",
            unique_together={("user", "fcm_token")},
        ),
        migrations.AddField(
            model_name="coupon",
            name="applicable_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all categories",
                related_name="coupons",
                to="backend.category",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products",
                related_name="coupons",
                to="backend.product",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="applicable_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all services",
                related_name="coupons",
                to="backend.service",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="backend.coupon",
            ),
        ),
        migrations.AddField(
            model_name="couponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="backend.coupon",
            ),
        ),
        migrations.AddField(
            model_name="couponusage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to="backend.order",
            ),
        ),
        migrations.AddField(
            model_name="couponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to="backend.user",
            ),
        ),
    ]
