# Generated by Django 5.2.5 on 2026-03-10 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_order_accepted_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Amount credited to referrer's wallet per successful referral (in ₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=300,
                        help_text="Minimum first order amount for referred user to qualify (in ₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "max_wallet_usage_percent",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum % of order total that can be paid using referral wallet",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reward_hold_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Number of days to hold referral reward before it can be approved/credited",
                    ),
                ),
                (
                    "max_referrals_per_day",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of referrals that can earn rewards per referrer per day",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referral Settings",
                "verbose_name_plural": "Referral Settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals_made",
                to="backend.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="backend.order",
                    ),
                ),
                (
                    "service_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="backend.servicebooking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        help_text="Code used during signup", max_length=20
                    ),
                ),
                ("reward_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rewarded", "Rewarded"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("fraud_reason", models.CharField(blank=True, max_length=255)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("signup_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hold_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Reward can be approved after this datetime",
                        null=True,
                    ),
                ),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_referred_set",
                        to="backend.user",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_referrer_set",
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "ordering": ["-created_at"],
                "unique_together": {("referrer", "referred_user")},
            },
        ),
    ]
