# Generated by Django 4.2.29 on 2026-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_service_vendor_and_service_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicevendortoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
