# Generated by Cursor on 2026-03-30

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_alter_servicevendortoken_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trial_enabled_areas", models.JSONField(blank=True, default=list, help_text="List of serviceable areas where trial is enabled")),
                ("trial_fee", models.PositiveIntegerField(default=0, help_text="Trial fee in ₹")),
                ("max_trial_items", models.PositiveIntegerField(default=3, help_text="Maximum items allowed in a single trial booking")),
                ("trial_discount_enabled", models.BooleanField(default=True, help_text="If true, trial fee can be applied as discount on conversion order")),
                ("trial_slots", models.JSONField(blank=True, default=list, help_text='List of time slots (e.g. ["morning","evening"])')),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trial Settings",
                "verbose_name_plural": "Trial Settings",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TrialBooking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("address", models.TextField(max_length=5000)),
                ("area", models.CharField(max_length=200)),
                ("trial_fee", models.PositiveIntegerField(default=0)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trial_date", models.DateField()),
                ("time_slot", models.CharField(max_length=50)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_trial",
                        to="backend.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_bookings",
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trial Booking",
                "verbose_name_plural": "Trial Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "dress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_items",
                        to="backend.productoption",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="backend.trialbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trial Item",
                "verbose_name_plural": "Trial Items",
                "unique_together": {("trial", "dress")},
            },
        ),
        migrations.AddField(
            model_name="order",
            name="trial_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked trial booking if this order was converted from a trial",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="backend.trialbooking",
            ),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(fields=["user", "created_at"], name="backend_tri_user_id_8d6e36_idx"),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(fields=["status", "created_at"], name="backend_tri_status_8414f0_idx"),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(fields=["payment_status", "created_at"], name="backend_tri_payment_24bca7_idx"),
        ),
    ]

