# Generated by Django 4.2.29 on 2026-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_trial_at_home_upsell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="max_bookings_per_date",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of bookings allowed per date (0 = unlimited)",
            ),
        ),
    ]
