# Generated by Django 4.2.29 on 2026-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_alter_product_max_bookings_per_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="trial_enabled",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, customers can book Trial-at-Home for this vendor's products",
            ),
        ),
    ]
