# Generated by Django 4.2.29 on 2026-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_vendor_trial_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="pincode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vendor pincode (used to filter categories by location)",
                max_length=10,
            ),
        ),
    ]
