# Generated by Django 4.2.29 on 2026-03-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0025_vendor_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialbooking",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor responsible for this trial booking (single-vendor enforced at creation)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trial_bookings",
                to="backend.vendor",
            ),
        ),
        migrations.AddField(
            model_name="trialbooking",
            name="vendor_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trialbooking",
            name="vendor_decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Vendor accepted/rejected the trial request",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trialbooking",
            name="vendor_message",
            field=models.TextField(
                blank=True, default="", help_text="Optional vendor note/message"
            ),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(
                fields=["vendor", "vendor_decision", "created_at"],
                name="backend_tri_vendor__c0630a_idx",
            ),
        ),
    ]
