# Generated by Django 4.2.29 on 2026-04-02 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0026_trialbooking_vendor_trialbooking_vendor_decided_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenViewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("screen", models.CharField(db_index=True, max_length=150)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Computed on end (seconds)"
                    ),
                ),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screen_view_events",
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screen analytics event",
                "verbose_name_plural": "Screen analytics events",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["screen", "started_at"],
                        name="backend_scr_screen_15339c_idx",
                    ),
                    models.Index(
                        fields=["user", "started_at"],
                        name="backend_scr_user_id_3d89f7_idx",
                    ),
                    models.Index(
                        fields=["device_id", "started_at"],
                        name="backend_scr_device__ddf4ad_idx",
                    ),
                ],
            },
        ),
    ]
