# Generated by Django 4.2.29 on 2026-04-02 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0027_screenviewevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLocationPing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy_m", models.FloatField(default=0)),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_pings",
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer location ping",
                "verbose_name_plural": "Customer location pings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "created_at"],
                        name="backend_cus_device__d8269e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="backend_cus_user_id_8f9292_idx",
                    ),
                ],
            },
        ),
    ]
