# Generated by Django 4.2.29 on 2026-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_customerlocationping"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="serviceable_locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select multiple pincodes/areas where this vendor operates. Used for category filtering.",
                related_name="vendors",
                to="backend.serviceablelocation",
            ),
        ),
    ]
