"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import requests

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-z)3ufq8vue4cy_%+4)$*at%6=3vxsx&ke=3@pt$jqbvgwqvbpr',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    '.vercel.app',
    '127.0.0.1',
    'localhost',
    '10.0.2.2',
    '13.205.169.178',  # AWS EC2
]
_extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS.extend(h.strip() for h in _extra_hosts.split(',') if h.strip())

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://13.205.169.178,http://13.205.169.178:8000,'
        'https://13.205.169.178,https://13.205.169.178:8000',
    ).split(',')
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    'backend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
            ssl_require=True,
        )
    }
elif os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
  #  {
   #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TIME_ZONE =  'Asia/Kolkata'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

JAZZMIN_SETTINGS = {
    "welcome_sign": "Welcome to the Rental Admin Panel",

}

#JAZZMIN_UI_TWEAKS = {
 #   "theme": "darkly",
#}



MEDIA_URL = '/media/'
MEDIA_ROOT =os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES_BASE_URL = os.environ.get(
    'TEMPLATES_BASE_URL',
    'https://clickwelladmin.pythonanywhere.com',
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_USE_TLS = True
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'clickwell2005@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'TwQ5OsXc3VASmhvj')

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://10.0.2.2:8000,http://127.0.0.1:8000,http://10.154.252.150:8000,'
        'http://89.117.157.199,http://192.168.29.118,'
        'http://13.205.169.178,http://13.205.169.178:8000',
    ).split(',')
    if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'backend.authentication.TokenAuthentication',
        'rest_framework.permissions.AllowAny',
    ]
}


FAST2SMS_API_KEY = os.environ.get(
    'FAST2SMS_API_KEY',
    'MzkN1BbwZKQvPk2JuEbyS9rFr6gKF7OsNVUYtMXUBVyGLoPubFugUzNDSfCa ',
)

TWO_FACTOR_API_KEY = os.environ.get(
    'TWO_FACTOR_API_KEY',
    '373a716f-a4fa-11f0-b922-0200cd936042',
)

# HyperSender WhatsApp API (OTP via WhatsApp instead of SMS)
# Get from https://app.hypersender.com - use env vars in production
HYPERsender_API_KEY = os.environ.get("HYPERsender_API_KEY", "1119|HK5rlDllCrK9x0UqdZTRtBcMLtjg14z43q0YZ8A8ae7047f0")
HYPERsender_INSTANCE_ID = os.environ.get("HYPERsender_INSTANCE_ID", "a11fec5f-d083-43ee-af5e-b5dda6e3a6d5")
HYPERsender_WHATSAPP_BASE_URL = "https://app.hypersender.com/api/whatsapp/v2"

# -----------------------------------------------------------------------------
# Referral share link – must point to a URL you control or to app stores
# -----------------------------------------------------------------------------
# When users share a referral link (e.g. via WhatsApp), this is the URL that opens.
# - If you have a website with signup: use e.g. https://yourdomain.com/signup
# - If you only have the app: use your Google Play app link so the friend can download.
#   Example: https://play.google.com/store/apps/details?id=com.yourcompany.rentalcothes
# - Do NOT use yourapp.com – it is a placeholder and shows "domain for sale".
REFERRAL_SIGNUP_BASE_URL = os.environ.get(
    "REFERRAL_SIGNUP_BASE_URL",
    "https://play.google.com/store/apps/details?id=com.chaitanya.rentalcothes",  # Your Android app – replace with your website signup URL if you prefer
)







# 🔹 APNs Certificate Configuration for PythonAnywhere
APNS_CA_CERT_PATH = os.path.join(BASE_DIR, "core", "USERTrust_RSA.crt")

# 🔹 Ensure requests module uses the correct CA certificate
requests_session = requests.Session()
requests_session.verify = APNS_CA_CERT_PATH

# 🔹 If using pyapns2 for push notifications, configure the certificate
try:
    from apns2.client import APNsClient
    from apns2.credentials import TokenCredentials

    APNS_CERT_PATH = "/home/Clickwelladmin/DjangoAdmin/clickwell-backend/core/USERTrust_RSA.crt"

    credentials = TokenCredentials(auth_key_path="path/to/AuthKey.p8")
    apns_client = APNsClient(
        credentials=credentials,
        use_sandbox=False,
        root_certificates=APNS_CERT_PATH
    )
except ImportError:
    apns_client = None  # Ensure this doesn't break Django if pyapns2 isn't installed

# Logging for APNs
import logging
logger = logging.getLogger(__name__)
logger.info(f"APNs Certificate Path: {APNS_CA_CERT_PATH}")

# FCM push notifications (e.g. when vendor accepts order).
import json

import firebase_admin
from firebase_admin import credentials

_FIREBASE_JSON = os.path.join(str(BASE_DIR), 'backend', 'beautyonclick-45c23-firebase-adminsdk-fbsvc-e78a918a62.json')
_FIREBASE_ENV = os.environ.get('FIREBASE_CREDENTIALS_JSON', '').strip()

if _FIREBASE_ENV:
    FIREBASE_ADMIN_CREDENTIALS = credentials.Certificate(json.loads(_FIREBASE_ENV))
    print('FCM: Credentials loaded from FIREBASE_CREDENTIALS_JSON env var')
elif os.path.isfile(_FIREBASE_JSON):
    FIREBASE_ADMIN_CREDENTIALS = credentials.Certificate(_FIREBASE_JSON)
    print(f'FCM: Credentials loaded from {_FIREBASE_JSON}')
else:
    FIREBASE_ADMIN_CREDENTIALS = None
    print('FCM: No Firebase credentials configured - push notifications disabled')



